#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <gui_handler.hpp>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>
#include <QAction>
#include <QPalette>
#include <QInputDialog>
#include <QDir>
#include <QMessageBox>

namespace Ui {
class MainWindow;
}

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    QTabWidget *tabWidget;                                                                              // Container to hold all tabs and tab widgets
    explicit MainWindow(QWidget *parent = 0);                                                           // Constructor made by Qt
    QAction *keyboard_left, *keyboard_right, *keyboard_up, *keyboard_down, *keyboard_i, *keyboard_m;    // Keyboard shortcuts
    ~MainWindow();

private:
    Ui::MainWindow *ui;                                                                                 // Generated by Qt
    QWidget *centralWidget;                                                                             // Container to hold everything
    gui_handler* gui_handler_;                                                                          // gui_handler, extremely important
    QWidget *Game;                                                                                      // Game tab
    QWidget *Inventory;                                                                                 // Inventory tab
    QWidget *Map;                                                                                       // Map tab
    QWidget *title_screen;                                                                              // Title Screen container
    void initialize_title_screen();                                                                     // Initializes the title screen
    QString playerName;                                                                                 // Player name for gui_handler.

private slots:
    void change_to_map();                                                                               // When changed to map - Disable controls and change tab.
    void change_to_inventory();                                                                         // Change to inventory - Disable controls and change tab.
    void initialize_new_game();                                                                         // Intialize a new game.
    void showAbout();                                                                                   // Shows credits.
};

#endif // MAINWINDOW_H
